# Generated by Django 2.1.1 on 2018-09-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=200)),
                ('owner', models.CharField(default=None, max_length=200)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
