# Generated by Django 2.1.1 on 2018-09-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='routing_number',
            field=models.IntegerField(max_length=16, null=True),
        ),
    ]
