# Generated by Django 2.1.1 on 2018-09-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180918_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isInGoodStanding',
            field=models.BooleanField(default=True),
        ),
    ]
