# Generated by Django 2.1.1 on 2018-09-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_account_isingoodstanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.CharField(default='UCU', max_length=200, null=True),
        ),
    ]
