# Migrations seem to be app specific

# Generated by Django 2.1.1 on 2018-10-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings')], default=None, max_length=200)),
                ('creator', models.CharField(default=None, max_length=200)),
                ('holder', models.CharField(default=None, max_length=200)),
                ('balance', models.IntegerField(default=0)),
                ('bank', models.CharField(choices=[('UCU', 'UCU'), ('Chase', 'Chase'), ('Wells Fargo', 'Wells Fargo')], default='UCU', max_length=200, null=True)),
                ('routing_number', models.IntegerField(null=True)),
            ],
        ),
    ]
