# Generated by Django 2.1.1 on 2018-10-02 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_auto_20181001_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='account_type',
        ),
    ]
