# Generated by Django 2.1.1 on 2018-11-05 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_accounts', '0004_internaltransferreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTransferReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=500)),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='externaltransferreceipt_from_account', to='bank_accounts.Account')),
                ('payee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='externaltransferreceipt_payee', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='externaltransferreceipt_payer', to=settings.AUTH_USER_MODEL)),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='externaltransferreceipt_to_account', to='bank_accounts.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='internaltransferreceipt',
            name='from_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internaltransferreceipt_from_account', to='bank_accounts.Account'),
        ),
        migrations.AlterField(
            model_name='internaltransferreceipt',
            name='to_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internaltransferreceipt_to_account', to='bank_accounts.Account'),
        ),
    ]
